### ISSUE TITLE
微信注册模块

### ISSUE THREAD

**Issue by lll123github** [e-dialect/hinghwa-dict-uni-app#100]

**Comment by FrogDar** [comment]
https://developers.weixin.qq.com/community/develop/doc/00022c683e8a80b29bed2142b56c01
感觉需要注意一下这个头像获取问题

**Comment by zzy2695s** [comment]
嗯嗯 这两天确实在这卡住了。我感觉有两种思路，一种是直接弹出一个窗口获取微信昵称头像登录；一种就是有另一个微信注册的页面，用户还是要填写用户名和密码（因为我看接口现在必须要这两个参数？）。我这两天一直写的后者但是感觉写着写着思路不太对

**Comment by FrogDar** [comment]
其实我甚至感觉页面都可以复用、、

**Comment by zzy2695s** [comment]
好像 确实欸 我去看看orz
