### ISSUE TITLE
quiz 模块代码分布

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-uni-app#104]
有一个工程方面的问题是，我看你现在全部的组件都是放在 `pages/components` 底下，然后非常零散
我的建议是对这些布局有一些谋划，比如 quiz 相关的呢 都放在 `pages/tools/quiz` 底下，然后其他的文件在下次有更新的时候也逐渐转移。

这个其实是我之前为什么大力推荐 `toXXXPage` 的原因，方便后续更改
（老早就想重新划分文件夹了，但是重构成本太大，只能是对新的这些文件进行处理了）

你可以使用 `WebStorm` 辅助进行这个过程）

_Originally posted by @FrogDar in https://github.com/e-dialect/hinghwa-dict-uni-app/issues/102#issuecomment-1374856322_

**Comment by FrogDar** [comment]
既然整理了其实我希望一步到位 https://eslint.vuejs.org/rules/multi-word-component-names.html
可以看到组件的名字应该是由多个单词组成，然后是 PascalCase（大驼峰） 比如 `CoolComponent`

**Comment by zzy2695s** [comment]
学长 目前组件的名称应该都已经遵循了PascalCase的命名方式 是其他页面还需要按照这个命名规则来更改吗 比如articleliked？
![image](https://user-images.githubusercontent.com/106298834/212235266-46c758d6-a999-4c07-b406-62f219fd0c36.png)

**Comment by FrogDar** [comment]
其他页面未来再弄吧 这个 PR 只管 quiz 的事情

**Comment by zzy2695s** [comment]
okok
