### ISSUE TITLE
规范页面命名规则

### ISSUE THREAD

**Issue by zzy2695s** [e-dialect/hinghwa-dict-uni-app#114]
既然整理了其实我希望一步到位 https://eslint.vuejs.org/rules/multi-word-component-names.html
可以看到组件的名字应该是由多个单词组成，然后是 PascalCase（大驼峰） 比如 `CoolComponent`

QuizIndexPage
QuizTesting
SingleQuiz
ScorePoster

之类的都可以参考

_Originally posted by @FrogDar in https://github.com/e-dialect/hinghwa-dict-uni-app/issues/104#issuecomment-1380748586_

**Comment by FrogDar** [comment]
嗯嗯 可以的  分类分类更清晰
每一个组件干嘛的都可以更明确

**Comment by zzy2695s** [comment]
> 嗯嗯 可以的 分类分类更清晰 每一个组件干嘛的都可以更明确

好嘞 我之后多去看看命名规范

**Comment by FrogDar** [comment]
不过我最新思考了一下
在 uni-app 里这个感觉并不适用
因为 uni-app 里面文件的名字也代表了他的组件名

在 #116 里做了尝试，去掉文件夹其实也不影响微信小程序的编译
因此，可以考虑：
- 组件仍然采用 [multi-word-component-names](https://eslint.vuejs.org/rules/multi-word-component-names.html) 这个规则
- 页面根据路由规则

对于 H5 来说，一个良好的路由还是能带来不错的观感的

**Comment by FrogDar** [comment]
对于那种非页面的组件，仍然是放在 `components` 文件夹里，未来或许也得建立子文件夹什么的方便收纳整理。

**Comment by FrogDar** [comment]
因为页面的路由和文件存放方式是对应的，所以以后pages底下估计会有一堆的东西）
不过目前看来估计会有：

- articles 文章相关（包括评论（评论在里面 comments 一波））
- words 词语相关（包括语音）
- quizzes 测试题相关
- login 登录、注册、忘记密码等
- me 个人相关
- users 用户相关

**Comment by FrogDar** [comment]
words 设想
- details.vue 词语详情
- pronunciations/upload.vue 上传语音 （pronunciations 文件夹）
- edit.vue 修改词条（未来预留）

**Comment by FrogDar** [comment]
login 设想
在 login 文件夹里：
- login.vue 登录页
- register.vue 注册页
- register/wechat.vue 微信注册页
- forget.vue 忘记密码页
