### ISSUE TITLE
反馈： 聪明花开 key 表达式

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-uni-app#123]
非 h5 平台 :key 不支持表达式 
![image](https://user-images.githubusercontent.com/20886330/212559491-6f68c66f-12b5-4b6d-a2aa-b883304d2008.png)

**Comment by zzy2695s** [comment]
我这里可以直接把‘question’之类的删掉吗？运行起来没问题

**Comment by FrogDar** [comment]
对 就是要全部删掉。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月16日(周一) 中午1:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [e-dialect/hinghwa-dict-uni-app] 反馈： 聪明花开 key 表达式 (Issue #123)




 
我这里可以直接把‘question’之类的删掉吗？运行起来没问题
