### ISSUE TITLE
横屏自动跳转失效

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-uni-app#126]
https://github.com/e-dialect/hinghwa-dict-uni-app/blob/3dacfc100d65dfc5a949d25b2bc8214e652175c3/src/App.vue#L10-L24

好像是官方文档没更新，这个平台是不是应该改成 h5 或者两种都有可能？
那这样的话 e.platform 那个地方就要写个 if 了
（现在在电脑的浏览器里打开也不显示跳转）

**Comment by zzy2695s** [comment]
我改成e.platform !== 'MP-WEIXIN'之后可以了

**Comment by FrogDar** [comment]
也可以也可以。
反正目前只有两个平台之后要兼容其他平台的时候再修正这个问题吧。
虽然我原本是想把这个判断改成说只有网页才有这个。
但是我不知道他那个网页这个字段应该等于多少，是H5还是wrb然后大小写是个什么情况？（所以先这么写也行吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月16日(周一) 下午3:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [e-dialect/hinghwa-dict-uni-app] 横屏自动跳转失效 (Issue #126)




 
我改成e.platform !== 'MP-WEIXIN'之后可以了

**Comment by zzy2695s** [comment]
我搜了下好像是写H5 但是写了H5好像不行嘞 先交这个吧

**Comment by FrogDar** [comment]
嗯嗯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月16日(周一) 下午3:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [e-dialect/hinghwa-dict-uni-app] 横屏自动跳转失效 (Issue #126)




 
我搜了下好像是写H5 但是写了H5好像不行嘞 先交这个吧
