### ISSUE TITLE
错误：访问其他人的个人页面

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-uni-app#128]
![image](https://user-images.githubusercontent.com/20886330/212609001-c325ccbb-203d-483d-bb51-092420171538.png)

背景图加载不出来 需要修复

类比 https://hinghwa.cn/users/5 选择性添加字段
（比如好做的：他创建的文章 有文章列表组件有数据）

**Comment by zzy2695s** [comment]
![image](https://user-images.githubusercontent.com/106298834/212618930-5fc42ade-871c-41e4-ab7f-b23e3517868a.png)
我这里可以加载出来欸

**Comment by FrogDar** [comment]
![Screenshot_2023-01-16-15-32-31-60_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/20886330/212622113-dd923ae7-88dd-4211-9047-58b2a741a2fd.jpg)

**Comment by FrogDar** [comment]
诶 我换了几个页面都不太行？
自己本地编译  m.pxm.test.edialect.top

**Comment by zzy2695s** [comment]
我这里是小程序可以但是H5不行orz

**Comment by FrogDar** [comment]
所以应该是他读取的那个图片路径有问题，你不要用那个什么相对的路径啊，你直接给他换成。一个网址。
那个网址的话 你可以在那个个人页面里找到（因为之前应该也同样的修过这个问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月16日(周一) 下午3:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [e-dialect/hinghwa-dict-uni-app] 错误：访问其他人的个人页面 (Issue #128)




 
我这里是小程序可以但是H5不行orz

**Comment by zzy2695s** [comment]
okok

**Comment by zzy2695s** [comment]
怪了 这俩链接是一样的。

**Comment by FrogDar** [comment]
![Screenshot_2023-01-16-16-36-31-90_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/20886330/212633500-2cd22982-22db-4ae0-ad32-5c0f49d48ea5.jpg)

**Comment by zzy2695s** [comment]
找到了是样式的问题orz
