### ISSUE TITLE
错误：个人信息页面头像无法正常上传

### ISSUE THREAD

**Issue by zzy2695s** [e-dialect/hinghwa-dict-uni-app#132]
**描述错误**
个人信息页面头像无法正常上传

**屏幕截图**
![image](https://user-images.githubusercontent.com/106298834/212629811-9bc1a60f-5029-4195-a6ed-75cbad7938c9.png)

**Comment by FrogDar** [comment]
感觉是没有加载到存储的那些信息？

**Comment by FrogDar** [comment]
还是说这里其实有两个不同的错误啊）

**Comment by zzy2695s** [comment]
> 还是说这里其实有两个不同的错误啊）

应该不是吧 我只有传头像的时候才会弹出这个错误 而且头像也不会改变

**Comment by FrogDar** [comment]
https://github.com/e-dialect/hinghwa-dict-uni-app/blob/71f69b89a6db0d24d88dda5fe2105b6d5cce5087/src/pages/about/userinfo/userinfo.vue#L153-L169

这个可以替换成 `services/file.js` 有一个 `chooseAndUploadAnImage` 试试看

**Comment by FrogDar** [comment]
还有就是感觉这个界面很奇怪 读取一些信息了 又不写入全局（app.gloabalData） 
其实应该是要写入全局 然后从 app.gloabalData 读取数据

**Comment by zzy2695s** [comment]
okok
