### ISSUE TITLE
错误：工具界面滚动问题

### ISSUE THREAD

**Issue by zzy2695s** [e-dialect/hinghwa-dict-uni-app#172]
工具界面滚动存在问题，导航栏遮挡了跳转图片

![image](https://user-images.githubusercontent.com/106298834/227121858-74d8f875-ab7c-4cbd-8848-10848f1ae3cf.png)

**Comment by FrogDar** [comment]
这个好做嘛）  难道是直接给它 加一个高度？ good first issue 得讲一下解决方法hh）

**Comment by zzy2695s** [comment]
哦哦这样
有两种方法 修改scroll view组件的属性或者在底部加一个有一定高度的view



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月24日 20:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [e-dialect/hinghwa-dict-uni-app] 错误：工具界面滚动问题 (Issue #172) |

这个好做嘛） 难道是直接给它 加一个高度？ good first issue 得讲一下解决方法hh）
