### ISSUE TITLE
建议：把聪明花开放到欢迎页面上

### ISSUE THREAD

**Issue by Topology2333** [e-dialect/hinghwa-dict-uni-app#203]
**描述这个功能的使用场景**

把聪明花开放到欢迎页面上，这样要玩聪明花开就只需要点击一次了。

**Comment by lin594** [comment]
真的有必要把他的优先级提的这么出来吗？现在的话应该只要点两下就可以吧？
首页那边其实是有一个推荐的文章列表，直接更新内容就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月5日(周二) 下午5:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [e-dialect/hinghwa-dict-uni-app] 建议：把聪明花开放到欢迎页面上 (Issue #203)




 
描述这个功能的使用场景
 
把聪明花开放到欢迎页面上，这样要玩聪明花开就只需要点击一次了。

**Comment by Topology2333** [comment]
> 真的有必要把他的优先级提的这么出来吗？现在的话应该只要点两下就可以吧？ 首页那边其实是有一个推荐的文章列表，直接更新内容就可以了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月5日(周二) 下午5:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [e-dialect/hinghwa-dict-uni-app] 建议：把聪明花开放到欢迎页面上 (Issue #203) 描述这个功能的使用场景 把聪明花开放到欢迎页面上，这样要玩聪明花开就只需要点击一次了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

有道理的、
