### ISSUE TITLE
建议：让密码长度超过11位可以达到20位

### ISSUE THREAD

**Issue by lll123github** [e-dialect/hinghwa-dict-uni-app#22]
**描述这个功能的使用场景**
个人的惯用密码是13位的，这恰巧超出了密码的最高位数。注册的时候无法使用13位的密码进行注册

**描述这个功能的具体内容**
提升容许设定的密码位数，可以到达20位

**描述可能的解决方案**
暂未考虑

**附加内容**
可以设定密码的设置要求，例如要求包含字母大小、符号、数字四种中的三种

**Comment by charlie0129** [comment]
13位确实少了，例如 32 位之类比较合理

**Comment by FrogDar** [comment]
https://github.com/e-dialect/hinghwa-dict-uni-app/blob/5298eab828793bd82aa32f057b6eb3a0c8eacdcd/src/pages/register/register.vue#L182-L188

这个确实前端应该修改，不过应该前后端都进行设置 双重验证

**Comment by charlie0129** [comment]
密码位数已更新。密码复杂度考虑到用这个网站规模和用户群体，暂时不启用。
