### ISSUE TITLE
建议：阻止用户连续发送验证码

### ISSUE THREAD

**Issue by lll123github** [e-dialect/hinghwa-dict-uni-app#23]
**描述这个功能的使用场景**
在任何使用验证码进行验证的场景，包括但不限于注册

**描述这个功能的具体内容**
要求在单功能界面下（如注册界面）需要等待半分钟之后再允许再次发送验证码。两个不同功能的界面发送验证码无影响。

**描述可能的解决方案**
暂无考虑到

**附加内容**
与网络安全相关，防止因受到攻击导致服务器崩溃。推荐一个网站叫做测试鸭：https://ce.mianshiya.com/

**Comment by lll123github** [comment]
> 这个 issue 主要是后端要做的事，要修的话后端也要

确实是，我在后端也加一下

**Comment by FrogDar** [comment]
主要是在注册页面和忘记密码页面

**Comment by zzzYmq** [comment]
OK
