### ISSUE TITLE
规范代码命名风格

### ISSUE THREAD

**Issue by charlie0129** [e-dialect/hinghwa-dict-uni-app#3]
一个好的代码规范是一个项目的门面，推荐参考 Airbnb 的 JavaScript 规范：https://github.com/airbnb/javascript#naming-conventions

目前代码中的变量命名并不规范，例如：

https://github.com/e-dialect/hinghwa-dict-uni-app/blob/751a9b3182a09dc3f3a57330e7b6e845ac82afe9/src/pages/register/register.vue#L40-L41

这个样例中存在这几个问题：
- 没有使用 camelCase
- 看到这两个变量 ，我们并不知道 1 2 指什么，意义不明，相信你看到这个代码时也有这种感觉，**这会给维护代码带来很大的难度**。需要更加具体的名称

代码中类似的地方还有很多（当然不是完全一样的情况），需要将它们统一一下，你可以参照上面的 Airbnb 的 JavaScript 规范来评估是否有问题。当然，整个项目都改那工作量可能大了，你可以只改几个文件。

git commit message 可以写 `style: xxxx`

**Comment by FrogDar** [comment]
修完这个 issue 可以去看看 #22

**Comment by FrogDar** [comment]
因为重构的原因估计早就变动了、 后续再开新 issue 吧
