### ISSUE TITLE
导航栏的字体飘在上面

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-uni-app#37]
感觉这个导航栏的字飘在上面，我再去看一看

_Originally posted by @zzy2695s in https://github.com/e-dialect/hinghwa-dict-uni-app/issues/36#issuecomment-1193108621_

**Comment by FrogDar** [comment]
漂浮这个样式问题可能会在其他用了这个组件的地方也出现）
（不过 H5 编译出来效果还行，这个看的不太好估计是 h5 和 微信小程序端的差异、、）
可能要去 colorui 底下的 custom 那个组件去改一改样式了、、
（可能是被我改烂了x）

**Comment by zzy2695s** [comment]
好嘞好嘞（不会不会 应该问题不大~）

**Comment by FrogDar** [comment]
![image](https://user-images.githubusercontent.com/20886330/180725789-506353ab-6ef1-4f03-aadd-7cc3031cb15a.png)

确实在H5上面表现还挺好的x
