### ISSUE TITLE
错误：文章底部评论区被发送评论栏遮挡

### ISSUE THREAD

**Issue by zzy2695s** [e-dialect/hinghwa-dict-uni-app#49]
当该文章评论较多时，滑动文章的评论区到最底部，发送评论的组件会挡住最后一个评论，影响观感

希望评论区可以划到最下方时，最后一个评论显示在发送评论栏上方

![5b20f81d154eda07b7d65ff57ae2231](https://user-images.githubusercontent.com/106298834/182579223-42084725-3561-4d25-8c00-33df3ca4860e.jpg)

**Comment by FrogDar** [comment]
可以通过添加滚动条的长度来解决
或者比如在最后一个评论下方再添加足够长的空白？（虽然这个方法貌似治标不治本x）

**Comment by zzy2695s** [comment]
ok我都试试
