### ISSUE TITLE
错误：文章首页点赞数不能及时更新

### ISSUE THREAD

**Issue by zzy2695s** [e-dialect/hinghwa-dict-uni-app#53]
在文章界面点赞后，文章首页的点赞数不能及时更新

希望点赞数能及时更新

![9d324e7c6015cc0c22f3c0a769068c7](https://user-images.githubusercontent.com/106298834/183254256-9a23df73-216d-4fae-ae53-473ae35d6604.jpg)
![e39d56b4a5acc0b10ecf2c9e1ee705c](https://user-images.githubusercontent.com/106298834/183254265-4b163653-0445-44fc-9a29-6946bf399958.jpg)

**Comment by zzy2695s** [comment]
这两个界面 文章首页还没有重构代码 点赞数用的函数不一样 我暂时卡住了orz

**Comment by FrogDar** [comment]
> 这两个界面 文章首页还没有重构代码 点赞数用的函数不一样 我暂时卡住了orz

其实这个应该是重新获取当前这个列表的内容

你可以先重构一个函数 `getArticles(page, pageSize)` （放在 services 里类似于其他的那些函数）

然后呢 有一个下拉刷新功能，你只要支持 下拉更新之后他是新的就行
