### ISSUE TITLE
反馈：聪明花开交互逻辑调整

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-uni-app#74]
- [ ] 正确答案的 1 2 3 改成 甲乙丙
- [x] 语记·随机测试 -》 聪明花开
- [x] 点击按钮应该是一整行都能点击才对，而不是只有一个小圆圈可以选
- [x] 提交后，答案和解析应该自动显示
- [x] 向左滑动进入下一题

**Comment by zzy2695s** [comment]
学长学长 我感觉 选项改成甲乙丙有点点奇怪 可能一般选项序号不太会用到
