### ISSUE TITLE
错误：用户信息界面显示服务器错误

### ISSUE THREAD

**Issue by zzy2695s** [e-dialect/hinghwa-dict-uni-app#94]
**描述错误**
在用户信息界面一点击修改信息就显示服务器错误

**预期行为**
应该可以正常修改

**屏幕截图**
![Uploading 0d7f451c2f88bdb9e178c141d3e7164.jpg…]()

**Comment by FrogDar** [comment]
已经复现该错误

**Comment by FrogDar** [comment]
![image](https://user-images.githubusercontent.com/20886330/205017508-4c1881cb-d9a9-470a-be4a-27564e558243.png)

本质上是未登录

**Comment by FrogDar** [comment]
这说明两点问题

1. 该页面是不是没有经过重构，没有使用我们的 request.js ？ 所以没有接入统一的接口
2. 没有登录的请求也没有经过验证，让他照样查看信息，这样并不好，得认证一下

**Comment by FrogDar** [comment]
对应的也有两处修改
-[ ] 重构修改个人信息页面的业务请求代码，尽快完成重构
-[ ] 在进入个人页面之前首先使用 LG0103 接口验证自己的 Token 是否有效？如果有效的话可以直接更换新Token

**Comment by zzy2695s** [comment]
是的 这个界面还用的globaldata 相应的我都修改一下

**Comment by zzy2695s** [comment]
> ![image](https://user-images.githubusercontent.com/20886330/205017508-4c1881cb-d9a9-470a-be4a-27564e558243.png)
> 
> 本质上是未登录

对 就是他这个错误反馈的逻辑也不太对 只要有错误提示服务器错误

**Comment by FrogDar** [comment]
> > ![image](https://user-images.githubusercontent.com/20886330/205017508-4c1881cb-d9a9-470a-be4a-27564e558243.png)
> > 本质上是未登录
> 
> 对 就是他这个错误反馈的逻辑也不太对 只要有错误提示服务器错误

这个就是他原本的问题了、、 我们也没办法改  只能是直接用新的服务）

**Comment by zzy2695s** [comment]
> > > ![image](https://user-images.githubusercontent.com/20886330/205017508-4c1881cb-d9a9-470a-be4a-27564e558243.png)
> > > 本质上是未登录
> > 
> > 
> > 对 就是他这个错误反馈的逻辑也不太对 只要有错误提示服务器错误
> 
> 这个就是他原本的问题了、、 我们也没办法改 只能是直接用新的服务）

这个好像是他代码写的问题？不过反正要重构了没有关系hh
![151fb7d16e97fcfb5f33dd157f4a9fd](https://user-images.githubusercontent.com/106298834/205021635-dec24eb0-7e9d-4ce5-806a-a1ca655f13f3.jpg)

**Comment by FrogDar** [comment]
不知道期末前是否有进度？如果有的话可以先提交一下PR

**Comment by zzy2695s** [comment]
有的有的 因为需要改的界面比较多所以没改完 一直没提交
