### ISSUE TITLE
用户语音上传榜单

### ISSUE THREAD

**Issue by lll123github** [e-dialect/hinghwa-dict-uni-app#97]
周榜 月榜

后端在语音模块增加一个上传时间字段

**Comment by zzy2695s** [comment]
![image](https://user-images.githubusercontent.com/106298834/212528892-2814c30f-ade3-4e7a-bbf6-8034d5b29360.png)
学长我这个功能写在这个页面行吗 或者用户语音量那个界面？

**Comment by FrogDar** [comment]
用户语音量那个吧？
就是查看每个人贡献多少语音的时候有一个跳转按钮 跳转到排行榜

**Comment by zzy2695s** [comment]
okok
